import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { GeneratedWorksheet } from '../types';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: '#1a1a1a',
  },
  header: {
    borderBottom: '2pt solid #3b82f6',
    paddingBottom: 12,
    marginBottom: 20,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: '#1e3a8a',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: '#6b7280',
  },
  nameDate: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 8,
  },
  nameField: {
    fontSize: 10,
    color: '#374151',
    borderBottom: '1pt solid #d1d5db',
    width: '45%',
    paddingBottom: 2,
  },
  instructions: {
    backgroundColor: '#eff6ff',
    padding: 10,
    borderRadius: 4,
    marginBottom: 16,
    border: '1pt solid #bfdbfe',
  },
  instructionsLabel: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#1d4ed8',
    marginBottom: 4,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  instructionsText: {
    fontSize: 10,
    color: '#1e40af',
    lineHeight: 1.5,
  },
  question: {
    marginBottom: 14,
    paddingLeft: 4,
  },
  questionNumber: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: '#3b82f6',
    marginBottom: 3,
  },
  questionText: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#1f2937',
  },
  answerLine: {
    borderBottom: '1pt solid #e5e7eb',
    marginTop: 8,
    marginBottom: 4,
    width: '60%',
    height: 20,
  },
  option: {
    fontSize: 10,
    marginLeft: 16,
    marginTop: 3,
    color: '#374151',
  },
  answerKeySection: {
    marginTop: 20,
    paddingTop: 12,
    borderTop: '2pt dashed #d1d5db',
  },
  answerKeyTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: '#1e3a8a',
    marginBottom: 10,
  },
  answerKeyItem: {
    fontSize: 9,
    color: '#4b5563',
    marginBottom: 3,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: '1pt solid #e5e7eb',
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: '#9ca3af',
  },
});

interface WorksheetPDFProps {
  worksheet: GeneratedWorksheet;
}

export default function WorksheetPDF({ worksheet }: WorksheetPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{worksheet.title}</Text>
          <Text style={styles.subtitle}>EduPrint AI - Intelligent Worksheet Platform</Text>
          <View style={styles.nameDate}>
            <Text style={styles.nameField}>Name: ____________________________</Text>
            <Text style={styles.nameField}>Date: ____________________________</Text>
          </View>
        </View>

        <View style={styles.instructions}>
          <Text style={styles.instructionsLabel}>Instructions</Text>
          <Text style={styles.instructionsText}>{worksheet.instructions}</Text>
        </View>

        {worksheet.content.map((item) => (
          <View key={item.number} style={styles.question}>
            <Text style={styles.questionNumber}>Question {item.number}</Text>
            <Text style={styles.questionText}>{item.question}</Text>
            {item.options ? (
              item.options.map((opt, i) => (
                <Text key={i} style={styles.option}>
                  {String.fromCharCode(65 + i)}) {opt}
                </Text>
              ))
            ) : (
              <View style={styles.answerLine} />
            )}
          </View>
        ))}

        <View style={styles.answerKeySection}>
          <Text style={styles.answerKeyTitle}>Answer Key</Text>
          <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
            {worksheet.answer_key.map((item) => (
              <Text key={item.number} style={[styles.answerKeyItem, { width: '50%' }]}>
                {item.number}. {item.answer}
              </Text>
            ))}
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by EduPrint AI</Text>
          <Text style={styles.footerText}>
            Page 1 of 1
          </Text>
        </View>
      </Page>
    </Document>
  );
}
